development:
  adapter: mysql2
  database: dianaonrails_development
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: dianaonrails_development
  username: root
  password: root
  pool: 5
  timeout: 5000


