development:
  adapter: mysql2
  database: dianaonrailsdb
  encoding: utf8
  host: dianaonrails.cl9uyjaaates.eu-west-1.rds.amazonaws.com
  username: dianaonrails
  password: dianaonrails
  reconnect: true
  port:3306

production:
  adapter: mysql2
  database: dianaonrailsdb
  encoding: utf8
  host: dianaonrails.cl9uyjaaates.eu-west-1.rds.amazonaws.com
  username: dianaonrails
  password: dianaonrails
  reconnect: true
  port:3306