development: 
    host: dianaonrails-cape8g7pab.elasticbeanstalk.com
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: dianaonrails_development
    pool: 5
    username: root
    password: root
    socket: /tmp/mysql.sock
test:
  host:dianaonrails-cape8g7pab.elasticbeanstalk.com
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dianaonrails_test
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

production:
  host: dianaonrails-cape8g7pab.elasticbeanstalk.com
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dianaonrails_production
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock