development: 
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: dianaonrails_development
    pool: 5
    username: root
    password: root
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dianaonrails_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dianaonrails_production
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock