development:
  adapter: mysql2
  database: dianaonrails_development
  username: root
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: dianaonrails_development
  username: root
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock


