development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dianaonrails_development
  pool: 5
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock
test:
  host: dianaonrailsdb.c1jujc6xlo5t.us-west-2.rds.amazonaws.com
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dianaonrails_test
  pool: 5
  username: root
  password: root

production:
  host: dianaonrailsdb.c1jujc6xlo5t.us-west-2.rds.amazonaws.com
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dianaonrailsdb
  port: 3306
  pool: 5
  username: dianaonrails
  password: dianaonrails