development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dianaonrails_development
  username: root
  password: 
  pool: 5


production:
  adapter: mysql2
  database: dianaonrails_production
  username: root
  password: 
  pool: 5
  timeout: 5000


