# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 007b88e22c7a34b1001b8b750ef65140ebc71bced4fef7dc0b664efd5792a97db2de3f8640dceec8c9092fda0f374aff4d399c8d7b0ad7615ac929c6815457cd

test:
  secret_key_base: a9fa80815cb20d79800166a4cffd4d2efcbf69380f35c5169fd5bf815eec2e6627e782b1e876fe809ca190496fc820db454df192f5965e9472235e0c04541cae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
